[project]
name = "self-stats"
version = "0.1.0"
description = "Generates a backup db for all my txn logs"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.1",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
]
