#!/bin/env bash

set -eu

 
interval=0

while getopts ":u:" opt; do
    case "$opt" in
        u)
            if [ "$OPTARG" -eq "$OPTARG" ] 2>/dev/null; then
                interval="$OPTARG"
            else
                echo "Error: -u requires a valid number."
                exit 1
            fi
            ;;
        \?)
            echo "Usage: $0 [-u interval]"
            exit 1
            ;;
    esac
done

# Shift to remove processed options from arguments
shift "$((OPTIND - 1))"

checktemp(){

    temperature_output=$(paste <(cat /sys/class/thermal/thermal_zone*/type) <(cat /sys/class/thermal/thermal_zone*/temp) | column -s $'\t' -t | sed 's/\(.\)..$/.\1°C/')

    # Print the temperature output
    echo "Temperature of Computer:"
    echo "$temperature_output"

}
export -f checktemp


if [ "$interval" -gt 0 ]; then
    watch -n "$interval" checktemp
else
    checktemp
fi
